language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: qnr7ETpCxDJX+l02Fsoi4MibbUltFxDBT3CeKWSPL3n+iz7sKJaZlR21n0RZ786d8GChjKjijWKebgs6pzPzQcUFK1qaIW7B89nw/mLQ9S8RcK0ijotFIyyfyqLqSDrIp9q30Zm9ZqsiUnPwepg6jw9fPDIpRNZ8DpXk41NY/4b4rbmUh5Ad/0pn+KKVYX2zSR2q3iIZMYCxN0XndYI8lGpfZyRzVIzDkT6s6s/YgpeWMsNyJVxS8o60L5sxGXvpJPgeLptrRk7FogjaTayRTOlM/3BILr77j3hl40MGlnpRdF1HnpbJ6D8MPUoIIbWjO6xsRuI7NUSmgHjbwMcIcJ+99H65UQSN0PpiZ3BuvCgKZXKkM+dB/uPuDDw6CtxiFu9eGOPeIjmx4G95sRptznYAFhbk3X9Yl2Gu+GXQiZo9gm7Tgl9HBhtsk4ZQVdTCTaW0VG0Ll4pn0X8M2u+FMeCKFZ8OUDahIhoUr8UQKEo/5OHB+M9krHB5G4S2odo1VDhPKLEq/vkk+JAOvVtxt0BErSsV7lferANd7ji1LurCYpDUwABfwynKDoP4CSNiZiQu37BtGw7YeJL0j8GjQ3zuM1OyKNMtBZQc6WBh0rz1p2t7i/yMp7X1X3w4LvIWGa073ltao3aSOrrn9eO3im5ZTHDUTvzTpnbv9SinChI=
  app: mysterious-woodland-75716
  on:
    repo: meron93/quote-catcher-api